### ISSUE TITLE
Clean Up 

### ISSUE THREAD

**Issue by raphir** [2sic/app-blog#20]
- [ ] List View: Any kind of 2sxc overlay triggers old/cached Styles upon closing the dialogue. -> bug or intended? 

- [x] Detail View: show arrows on next / previous post based on post object name. Solution now not satisfying.

- [x] Detail View: Social features not implemented yet.

**Comment by iJungleboy** [comment]
Note also that logged in, the blog gets wider (or the next/prev get closer) - so some CSS is added when logged in...
