### ISSUE TITLE
Delete Button in Toolbar not working. 

### ISSUE THREAD

**Issue by raphir** [2sic/app-blog#23]
- Alert Message that says that item is used somewhere else and can't be deleted.

**Comment by iJungleboy** [comment]
Is the message correct? If yes, it's not a bug. Or is it wrong?

**Comment by raphir** [comment]
![2017-03-06_09-00-11](https://cloud.githubusercontent.com/assets/19209321/23601380/77e0c394-024b-11e7-97b7-24fd8af06a2b.png)
![2017-03-06_09-02-12](https://cloud.githubusercontent.com/assets/19209321/23601432/b17e5e2c-024b-11e7-93d1-a5481dd7758a.png)

**Comment by iJungleboy** [comment]
So is the message correct? Is it in use somewhere?

**Comment by iJungleboy** [comment]
Seems to be a security-issue - delete is failing because of a protection-layer. Let me check...

**Comment by iJungleboy** [comment]
bug in 2sxc - issue https://github.com/2sic/2sxc/issues/1128 - just fixed
