### ISSUE TITLE
Button content items only accessible for administrators

### ISSUE THREAD

**Issue by raphir** [2sic/app-blog#25]
- [ ]  e.g. custom user created for blog not able to view list.

- [ ] note from 2rm: should all user roles have access to list view of blogs? 

### If user has rights to edit page - then the button works:
![2017-03-07_17-19-07](https://cloud.githubusercontent.com/assets/19209321/23666091/8c974db6-035a-11e7-870e-4a44b3e3aac7.png)

**Comment by iJungleboy** [comment]
will be fixed in the next version - https://github.com/2sic/2sxc/issues/1127
