### ISSUE TITLE
Nex and prev navigation does not apply category/tag filter

### ISSUE THREAD

**Issue by mangiove** [2sic/app-blog#27]
Hi all, just was wondering if the cool new feature next/prev navigation should consider the applied filters (categories,tags).
At the moment even if a category filter is applied the navigation goes through the blog posts that are not part of the filtered ones.

Thanks you

**Comment by iJungleboy** [comment]
This is an interesting note. At the moment it's not covered and I'm not sure if it can be, as each article could belong to multiple categories and it's not clear if these should limit the filter.

**Comment by erw13n** [comment]
Once I look at _pager.cshtml, there's a function LinkToPageNumber for handling pagination.
In my case I add 
`+ (!String.IsNullOrEmpty(Request.QueryString["category"]) ? "category=" + Request.QueryString["category"] + "&" : "")`
So the pagination also work on Category
Is there any better solution?

**Comment by iJungleboy** [comment]
closed in the contribution https://github.com/2sic/app-blog/pull/33
