### ISSUE TITLE
Error on blog post deletion

### ISSUE THREAD

**Issue by mcalado** [2sic/app-blog#3]
When deleting a blog post an error is fired.

**Comment by iJungleboy** [comment]
Could you clarify what you are deleting? the term "job" confuses me.

**Comment by mcalado** [comment]
I mean blog, I did a typo. I will provide more details for you. But during my tests I think the problem happens when trying to delete the blog post that you currently have opened. Sounds like it tries to redirect to the deleted item or something like.

**Comment by iJungleboy** [comment]
maybe you were on the blog details, then went to admin and deleted it?

**Comment by mcalado** [comment]
Please see bellow the error. It only happens while deleting the blog post that you're currently seeing, so not a big problem.

Error: System.InvalidOperationException: Sequence contains no elements at System.Linq.Enumerable.First[TSource](IEnumerable`1 source) at ASP._Page_Portals_0_2sxc_Blog_App__Post_Details_cshtml.Execute() in c:\inetpub\wwwroot\New\Portals\0\2sxc\Blog App_Post Details.cshtml:line 254 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.SexyContent.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 65 at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 75 at ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:line 89 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:line 200

**Comment by iJungleboy** [comment]
So basically this is a message saying that you're on the details page, but it didn't find any blog post with this url-id (because there is none). I think this is understandable, so if it's ok for you, we'll close this without fixing anything.
