### ISSUE TITLE
Blog - add Content or APP not working in 2sxc 9.9

### ISSUE THREAD

**Issue by wtatters** [2sic/app-blog#32]
See error screen shot below ...

Add New Blog entry 
While in the Post Body - click the add Content/App button -  a blue box is displayed - there does not seem to be any way to interact with this element - but moving on .

Save the BLOG and view the blog single page post - the blue app area is again displayed - this time with the hover Add Content / Add App hover showing -  if you click either option you get an error.

Westa

![image](https://user-images.githubusercontent.com/1026744/33204112-2ae3589a-d14e-11e7-9c62-3b751a075e79.png)

**Comment by iJungleboy** [comment]
I believe this is related to https://github.com/2sic/2sxc/issues/1334

I'll continue fixing it there, please follow that issue. It should be fixed by Monday or Tuesday.

**Comment by iJungleboy** [comment]
just fyi: I found the bug and it should be fixed monday/tuesday with 2sxc 9.10

**Comment by wtatters** [comment]
Excellent stuff - tests well now :)

**Comment by iJungleboy** [comment]
thx 👍
