### ISSUE TITLE
The Blog pages are created on the fly, so how we can get the this.Request.Url.AbsoluteUri?

### ISSUE THREAD

**Issue by mcalado** [2sic/app-blog#34]
The Blog pages are created on the fly, so how we can get the this.Request.Url.AbsoluteUri? Sounds like it always returns the blog page itself, not the blog item page. We've tried it using DNN code as well. Is there a way that we can collect the URL path on the fly for your component? Thanks in advance!

**Comment by iJungleboy** [comment]
There are a few options, quickest (but not nicest) is simply replicate the convention, using `Link.To(parameters: "post=" + post.UrlKey)` - or the `NavigateTo` equivalent of DNN. 

Internally DNN always rewrites the url, so anything in the path is treated as query-string parameters. AFAIK there is a DNN command or an HTTP-header to get the pre-rewritten url, but I would have to google that.

**Comment by mcalado** [comment]
Thank you!
