### ISSUE TITLE
Issue with Upgrade

### ISSUE THREAD

**Issue by mcalado** [2sic/app-blog#35]
Hi,

We have some problems in the process of updating the 2sxc blog module. At first the version of the 2sxc module running was version 8.4.8, I've tried to install the latest version which is 9.32.1 and during the installation process it returned an error which said that I had to have at least the version 8.2 of the 2sxc blog module installed if I wanted to upgrade to version 9.32.1, so I installed version 8.2 and it was
fine, then I tried once again to install version 9.32.1 and it did not work. After that, I managed to install version 9 and it worked ok, then with version 9 on, I did the process for version 9.32.1 over again and it returned the same error (asking for version 8.2) but at this  time in the installed extensions list the app appears with version 9.32.1 and the content with version 9.0.2 as you can see in the image (differentversions.jpg). Still, after this problem, I tried to install an older version to see if at least the versions for both app and content would match, but it did not, as you can see in the image (newerversion.jpg), it returns a failure during the process, saying that there's already a newer version installed. Please let me know if there is any log file that I can send to help you to identify the issue. Any help is very welcome, thanks!

![differentversions](https://user-images.githubusercontent.com/34480/45377291-8c82af80-b5d0-11e8-8f99-397d510997b0.jpg)

![newerversioninstalled](https://user-images.githubusercontent.com/34480/45377299-90163680-b5d0-11e8-93bf-56baea8e0f4e.jpg)

**Comment by iJungleboy** [comment]
This is a kind of bug in DNN - there is a certain randomness to what module it takes to verify it's been installed. So in your case, it's looking at the App-Module and sees it has a new version, but actually the entire engine is on 2sxc Content module. 

I recommend a simple fix: just manually change the version of the 2sxc-app module (in the dnn module settings) down to 9.x. Then the test will go through and you can install.

**Comment by mcalado** [comment]
The problem is that whenever I try to update the 2sxc blog extension, the 
process returns an error if I try to update for 
version 9.32, it says I must have at least version 8.12 installed, I also
have tried to install version 8.12 and it did not work, actually after all
the attempts I can see that the app extension is always with the latest 
version installed but the process does not take effect to the content extension, 
and also, if I try to install any of other previous versions it returns a 
series of exceptions in which the first one is: There is already an object 
named 'ToSIC_EAV_DataTimeline' in the database. Any help with this upgrade process is very welcome, this way we can move from EVOQ 8 to 9.

![a](https://user-images.githubusercontent.com/34480/45446864-5e6e9f80-b6a4-11e8-8ded-14d1e45efc0f.jpg)

![b](https://user-images.githubusercontent.com/34480/45446865-5e6e9f80-b6a4-11e8-8c35-c4c64ba18d6c.jpg)

**Comment by iJungleboy** [comment]
Thanks. Just to clarify a few things so we don't confuse each other

1. I assume you're installing 2sxc, not the 2sxc-blog. 2sxc is the generic data / edit engine, the blog is just one of many pre-built apps you can then install once 2sxc is installed. 
1. I assume you ran into trouble on a copy of the live system, is this correct?
1. Did your installation already have a 2sxc installed when you started, or is this a clean install? What version is it?
1. When you try something again, are you restarting from a copy of live, or could it be that your test-copy is already in a pretty messy state from many up/downgrades?

**Comment by mcalado** [comment]
Thank you again for the feedback.

	1) Yes.
	2) Yes.
	3) Yes. Please find attached the previous version.
	4) Yes, it's a copy of live and I can re-try that as many times we need. I can give it another try if you can advise the best steps based on what I have. Basically, we are upgrading from Evoq 8.2 to 9.1. After the upgrade we are having the blog component problem, so we are trying to install the latest version.

![blogevoq8](https://user-images.githubusercontent.com/34480/45498176-e78ee080-b74f-11e8-91cb-a51fec53e0be.PNG)

**Comment by iJungleboy** [comment]
So basically somewhere along the versions of 9, we removed a lot of upgrade scripts because we changed the data model and keeping the upgrade scripts could have had unintended consequences. So in your case, you should

1. Restart from a new copy of live
1. upgrade to 8.12
1. Upgrade to 9.32.1

and you should be fine. Could you try that, and if you run into any issues or everything works, pls post here - the next person will be grateful :)

**Comment by mcalado** [comment]
Thank you! I will give it a try. Do you think I need to upgrade to Evoq 9 before I try to upgrade your component or should I try to update your component before the upgrade to Evoq 9? Thanks.

**Comment by iJungleboy** [comment]
Either way should be absolutely no problem :)

**Comment by mcalado** [comment]
Unfortunately, it didn't work. But I have good news anyway: updating it only to 8.12 resolves our issue since it's working with Evoq 9.1. So we are all set, appreciate all your help, thanks a lot!

**Comment by iJungleboy** [comment]
ok. just fyi: it will probably fail with 9.2 and work again with 9.2.1 because of breaking changes in 9.2 for the Newtonsoft update. In 9.2.1 we contributed some code to DNN which unbroke the change. 

Note: if you would in try the upgrade again and post the long error text, I think ill be able to help - my guess is you have some leftover tables from previous versions/upgrades, which are hurting the version detection that rely on them.

**Comment by mcalado** [comment]
Thanks. At this moment I will keep it with 8.12 because it takes time to run the test environments. When I have all the upgrade in place, I can do more tries because it will be faster to do it, I will let you know, probably in about one or two weeks. Thanks for all your help!
